tem_graph:
  nodes:
    read:
      to: flip
    flip:
      type: FlipNode
    clahe:
      type: CLAHENode
    min_max_mean:
      type: MinMaxMeanNode
    preview_copy:
      type: CloneNode
    downscale:
      type: ResizeNode
      to: encode_preview
    to_gpu: null
    to_preview: null
