common:
  darkfield: "{{common.tile_dir}}/darkfield.tiff"
  brightfield: "{{common.tile_dir}}/brightfield.tiff"
  aperture_size: [3, 1]
  find_aperture_min_step: 1000
  gaussian_fit_decimation: 50
pytem:
  root: pytem.root.Root
  machines:
    Preview:
      DarkField:
        config:
          path: "{{common.darkfield}}"
      BrightField:
        config:
          path: "{{common.brightfield}}"
      FindAperture:
        config:
          aperture_size: "{{common.aperture_size}}"
          min_step: "{{common.find_aperture_min_step}}"
          tape_threshold: 50
      BeamSpread:
        config:
          std: 2500
        Fit:
          config:
            timeout: 5
            decimate_stride: "{{common.gaussian_fit_decimation}}"
        ChangeSpread:
          config:
            timeout: 2
      AutoFocus:
        ChangeFocus:
          config:
            timeout: 2
    Acquisition:
      DarkField:
        config:
          path: "{{common.darkfield}}"
      BrightField:
        config:
          path: "{{common.brightfield}}"
      FindAperture:
        config:
          aperture_size: "{{common.aperture_size}}"
          min_step: "{{common.find_aperture_min_step}}"
      BeamSpread:
        Fit:
          config:
            decimate_stride: "{{common.gaussian_fit_decimation}}"
        ChangeSpread:
          config:
            timeout: 2
