pytem:
  machines:
    - type: pytem.Root
      states:
        - name: Preview
          children: Preview
        - Acquisition
      initial: Preview
    - type: pytem.preview.Preview
      states:
        - name: AutoExposure
          children: AutoExposure
        - name: UpdateImage
          on_enter: prepare_frame
          children: PreviewRequest
      transitions:
        - source: UpdateImage_Request
          dest: AutoExposure
          trigger: success
          condition: auto_exposure
        - source: UpdateImage_Request
          dest: UpdateImage
          trigger: success
      initial: UpdateImage
    - type: pytem.auto_exposure.AutoExposure
    - type: pytem.preview.PreviewRequest
