pytem:
  machines:
    root:
      type: pytem.Root
      states:
        - name: Preview
          children: preview
        - Acquisition
      initial: Preview
    preview:
      type: pytem.preview.Preview
      states:
        - name: AutoExposure
          children: auto_exposure
          remap:
            Success: UpdateImage
        - name: UpdateImage
          on_enter: prepare_frame
          children: preview_request
      transitions:
        - source: UpdateImage_Request
          dest: AutoExposure
          trigger: success
          conditions: auto_exposure
        - source: UpdateImage_Request
          dest: UpdateImage
          trigger: success
      initial: UpdateImage
    auto_exposure:
      type: pytem.auto_exposure.AutoExposure
    preview_request:
      type: pytem.preview.PreviewRequest
      success_state: False
