pytem:
  root: pytem.root.Root
  machines:
    Preview:
      DarkField:
        config:
          path: "{{common.tile_dir}}/darkfield.tiff"
      BrightField:
        config:
          path: "{{common.tile_dir}}/brightfield.tiff"
