tem_graph:
  nodes:
    input:
      type: SubscribeRawTileNode
      to: read
      args:
        host: broker
    read:
      type: IMReadNode
      args:
        concurrency: serial
      to: to_gpu
    to_gpu:
      type: ToGPUNode
      args:
        concurrency: serial
      to: flip
    flip:
      type: FlipNodeGPU
      args:
        axis: horizontal
        concurrency: serial
      to: clahe
    clahe:
      type: CLAHENodeGPU
      args:
        concurrency: serial
      to:
        - min_max_mean
    min_max_mean:
      type: MinMaxMeanNodeGPU
      args:
        concurrency: serial
      to: send_min_max_mean
    send_min_max_mean:
      type: PublishMinMaxMeanNode
      args:
        host: broker
