tem_graph:
  nodes:
    input:
      type: SubscribeRawTileNode
      to: read
      args:
        host: broker
    read:
      type: IMReadNode
      args:
        concurrency: serial
      to: to_gpu
    to_gpu:
      type: ToGPUNode
      args:
        concurrency: serial
      to: flip
    flip:
      type: FlipNodeGPU
      args:
        axis: horizontal
        concurrency: serial
      to: clahe
    clahe:
      type: CLAHENodeGPU
      args:
        concurrency: serial
      to:
        - min_max_mean
        - preview_copy
        - montage_copy
        - to_save
    to_save:
      type: FromGPUNode
      args:
        concurrency: serial
      to: save
    save:
      type: IMWriteNode
      args:
        concurrency: serial
        extension: ".processed.tiff"
        output_dir: "{{common.tile_dir}}"
      to: send_processed
    send_processed:
      type: PublishFileNode
      args:
        host: broker
        topic: "tile.processed"
    min_max_mean:
      type: MinMaxMeanNodeGPU
      args:
        concurrency: serial
      to: send_min_max_mean
    send_min_max_mean:
      type: PublishMinMaxMeanNode
      args:
        host: broker      
    preview_copy:
      type: CloneNodeGPU
      to: preview_scale
      args:
        concurrency: serial
    preview_scale:
      type: ResizeNodeGPU
      args:
        concurrency: serial
        scale: 0.10
      to: preview_to_cpu
    preview_to_cpu:
      type: FromGPUNode
      args:
        concurrency: serial
      to: preview_encode
    preview_encode:
      type: Base64Node
      args:
        concurrency: serial
      to: preview_publish
    preview_publish:
      type: PublishImageNode
      args:
        host: broker
        topic: "tile.preview"
    montage_copy:
      type: CloneNodeGPU
      to: montage_scale
      args:
        concurrency: serial
    montage_scale:
      type: ResizeNodeGPU
      args:
        concurrency: serial
        scale: 0.03
      to: montage_to_cpu
    montage_to_cpu:
      type: FromGPUNode
      args:
        concurrency: serial
      to: montage_encode
    montage_encode:
      type: Base64Node
      args:
        concurrency: serial
      to: montage_publish
    montage_publish:
      type: PublishImageNode
      args:
        host: broker
        topic: "tile.minimap"        