services:
  broker:
    image: apache/activemq-artemis
    environment:
      ANONYMOUS_LOGIN: true
    ports:
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      timeout: 15s
      start_period: 10s
      test: ["CMD", "curl", "-f", "http://localhost:8161/"]
  pytem:
    image: 10.128.25.8/pytem
    command: pigeon-transitions --host broker /config/pytem.yaml
    volumes:
      - "config:/config"
      - "/tmp:/tmp"
    depends_on:
      ximea:
        condition: service_healthy
      config:
        condition: service_completed_successfully
  tem_graph:
    image: 10.128.25.8/tem_graph
    command: TEM_graph /config/tem_graph.yaml
    volumes:
      - "config:/config"
      - "/tmp:/tmp"
    depends_on:
      config:
        condition: service_completed_successfully
      broker:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
volumes:
  config:
