include:
  - base.yaml

services:
  ximea:
    image: 10.128.25.8/ximea_service
    command: XIMEA_service --host broker /config/ximea.yaml
    volumes:
      - "/tmp:/tmp"
      - "config:/config"
    depends_on:
      broker:
        condition: service_healthy
      config:
        condition: service_completed_successfully
    healthcheck:
      start_period: 10s
      test: timeout 5s pigeon --host broker -s camera.status --one || exit 1
